import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const openSans = localFont({
  src: '/fonts/OpenSans-VariableFont_wdth,wght.ttf',
  preload: false
})

//👇 Configure the object for our second font
const roboto = localFont({
  src: '/fonts/Roboto-VariableFont_wdth,wght.ttf',
  preload: false
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${openSans.className} ${roboto.className} grid min-h-svh grid-rows-[auto_1fr_auto] font-sans antialiased`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
